# runstack.yaml

# config
runtime: 5
generator: NORMAL
first_boot: No
antenna_deployed: No
interactive: No

# enable
modules:
  APRS:
    pfs_logging: True
    start_with_error: False
    reset_time: 0
  Iridium: {}
  EPS:
    state_filename: addr.state.i2c
    command_filename: addr.command.i2c
    address: 4
    reset_time: 0
  AntennaDeployer: {}

# tests (ignored if interactive is enabled)
actions:
    - [2, shutdown_aprs]
commands:
    - [4, print EPS]
    - [1.5, sfr TIME]
